language: ruby
rvm:
  - 2.2.2
addons:
  code_climate:
    repo_token:
      secure: "dUCLhoRnwDCjK+DDXTAx8f+J61oNGRp/cGaSg3rpEQKRwbCQFCZE/z8xElrNas5xsMCvIi0kCeRh+8hchB/mvaO01VvJQjtW1dyiN9MIOK88B/wb85Ga3vIdDwym3JGDL7RdGOgI1K/zRxchJg5kjyWCgSjD/eE2x1UNrsbgzMfxVbjAdnUVAv2iAeu1W1pMx+q39NBuIL7TaoXzUfEXHCh00PJWHHg30sz/8J3lEBV4aUuSCm0jbVQNcDihMIXUNyWOu7H126vTkiKKd4VRwXgP9fZWpNo93U/mb3GThYDI9+lbYvMTw7fHlfq11xuKuC8EC0yxJeQRe3KQeU8S+m1JDX3dBbSB7eFAEq+1fJGDp2k2bWiQyptX2bC2waXWVuijT+Ot2sPkG1W1xOfFHGEdv5nj+mcQCvUVbs2szKiSAPc3mySuaepghXGwlkvsG3h5RKfI5Hxybo/IrpIin3Ps6a1iSUhPUSCQRD2rcEqlKmeFV4uqgmqllKoJUiE8qb1dyAgjmCF6Iwl19iysgAoO6GtAoWvnVtBxmofOXxfLiIij9WjcgewqDbUXG5E9wkYcFiy3llc4DVFe8C3rGqMAt1CQXPwf+AGAAga/OqBwU2Rg4zg8vx8UBUEPfDasrUoUOUKbZ/gJBbL3RTTxeY+bpRX8rzMR5ly6+fjo/EI="
before_script:
  - psql -c 'create database good_books_test;' -U postgres
